[package]
name = "rustrays"
version = "0.1.0"
authors = ["Peter Lieber <41489571+peteralieber@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
log = "0.4.14"
png = "0.16.8"